name: DEMO DEV PIPELINE

on:
  push:
    branches:
    - 'dev*'
jobs:
  first_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
      
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Run Script
        run: |
          python hello.py
