name: DEMO DEV PIPELINE

on:
  push:
    branches:
    - '!*'
jobs:
  first_job:
    runs-on: ubuntu-latest
    env: |
      DAY_OF_WEEK: Mon
    strategy:
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
    
      - name: "Hello world when it's Monday"
        run: echo "Hello today is $DAY_OF_WEEK"
          
        
