name: DEMO DEV PIPELINE

on:
  push:
    branches:
    - '!*'
jobs:
  first_job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
          
        
